meta_data = {
        'sewer_type':{
            '1': {'desc':'None'},
            '2': {'desc':'Private'},
            '3': {'desc':'Commercial/Public'}
                },
        'water_supply':{
            '1':{'desc':'None'},
            '2':{'desc':'Private'},
            '3':{'desc':'Commercial/Public'}
                        },
        'utilities':{
            '1':{'desc':'None'},
            '2':{'desc':'Gas'},
            '3':{'desc':'Electric'},
            '4':{'desc':'Gas/Electric'}
        },
        'heat_type':{
            '1':{'desc':'No central heat'},
            '2':{'desc':'Hot air'},
            '3':{'desc':'Hot water/Stream'},
            '4':{'desc':'Electric'}
        },
        'fuel_type':{
            '1':{'desc':'None'},
            '2':{'desc':'Gas(natural or LP)'},
            '3':{'desc':'Electric'},
            '4':{'desc':'Oil'},
            '5':{'desc':'Wood'},
            '6':{'desc':'Solar'},
            '7':{'desc':'Coal'},
            '8':{'desc':'Geothermal heat'}
        },
        'prop_class' : {
            '100': { 'desc':'Agricultural'},
            '105': { 'desc': 'Agricultural Vacant Land (Productive)'},
            '110': { 'desc': 'Livestock and Products'},
            '111': { 'desc': 'Poultry and Poultry Products: eggs chickens turkeys ducks and geese'},
            '112': { 'desc': 'Dairy Products : Milk butter and cheese'},
            '113': { 'desc': 'Cattle Calves and hogs'},
            '114': { 'desc': 'Sheep and wool'},
            '115': { 'desc': 'Honey and Beeswax'},
            '116': { 'desc': 'Other livestock : Donkeys and goats'},
            '117': { 'desc': 'Horse Farms'},
            '120': { 'desc': 'Field Crops'},
            '129': { 'desc': 'Acquired Development Rights'},
            '130': { 'desc': 'Truck Crops - Mucklands'},
            '140': { 'desc': 'Truck crops - Not mucklands'},
            '150': { 'desc': 'Orchard crops'},
            '151': { 'desc': 'Apples Pears Peaches Cherries etc'},
            '152': { 'desc': 'Vineyards'},
            '160': { 'desc': 'Other fruits'},
            '170': { 'desc': 'Nursery and greenhouse'},
            '180': { 'desc': 'Speciality farms'},
            '181': { 'desc': 'Fur Products mink chinchilla etc'},
            '182': { 'desc': 'Pheasant etc'},
            '183': { 'desc': 'Aquatic oysterlands fish and aquatic plants'},
            '184': { 'desc': 'Livestock: deer moose llamas buffalo etc'},
            '190': { 'desc': 'Fish game and wildlife preserves'},
            '200': { 'desc' : 'Residential'},
            '210': { 'desc' : 'One family year-round Residential'},
            '215': { 'desc' : 'One family year-round Residential with accessory apartment'},
            '220': { 'desc' : 'Two family year around Residential'},
            '230': { 'desc' : 'Three family year around Residential'},
            '240': { 'desc' : 'Rural Residential with Acreage'},
            '241': { 'desc' : 'Primary Residential also used in agricultural production'},
            '242': { 'desc' : 'Recreational use'},
            '250': { 'desc' : 'Estate'},
            '260': { 'desc' : 'Seasonal Residentials'},
            '270': { 'desc' : 'Mobile home'},
            '271': { 'desc' : 'Multiple mobile homes'},
            '280': { 'desc' : 'Residential - Multi-Purpose/Multi-Structure'},
            '281': { 'desc' : 'Multiple Residentials'},
            '283': { 'desc' : 'Residential with Incidental commercial use'}  ,
            '300': { 'desc' : 'Vacant land'},
            '310': { 'desc' : 'Residential'},
            '311': { 'desc' :'Residential Vacant land'},
            '312': { 'desc' :'Residential land including a small improvement(not used for living accommodation)'},
            '314': { 'desc' :'Rural Vacant lots of 10 acres or less'},
            '315': { 'desc' :'Underwater vacant land'},
            '320': { 'desc' : 'rural'},
            '321': { 'desc' : 'Abandoned Agricultural land'},
            '322': { 'desc' : 'Residential vacant land over 10 acres'},
            '323': { 'desc' : 'Other rural vacant lands'},
            '330': { 'desc' : 'Vacant land located in commercial areas'},
            '331': { 'desc' : 'Commercial vacant land with minor improvements'},
            '340': { 'desc' : 'Vacant land located in Industrial areas'},
            '341': { 'desc' : 'Industrial vacant land with minor improvements'},
            '350': { 'desc' : 'Urban renewal or slum clearance'},
            '351': { 'desc' : 'Shell building - residential'},
            '352': { 'desc' : 'Shell building - commercial'},
            '380': { 'desc' : 'Public utility vacant land'},
            '400': { 'desc' : 'Commercial'},
            '410': { 'desc' :'Living accommodations'},
            '411': { 'desc' : 'Apartments'},
            '414': { 'desc' : 'Hotel'},
            '415': { 'desc' : 'Motel'},
            '416': { 'desc' : 'Mobile home parks(trailer parks trailer courts)'},
            '417': { 'desc' : 'Camps cottages and bungalows'},
            '418': { 'desc' : 'Inns lodges Boarding and rooming houses Tourist home Fraternity and Sorority houses'},
            '420': { 'desc' : 'Dining Establishments'},
            '421': { 'desc' : 'Restaurants'},
            '422': { 'desc' : 'Diners and luncheonettes'},
            '423': { 'desc' : 'Snack bars Drive-ins ice cream bars'},
            '424': { 'desc' : 'Night clubs'},
            '425': { 'desc' : 'bar'},
            '426': { 'desc' : 'Fast food franchises'},
            '430': { 'desc' : 'Motor Vehicle Services'},
            '431': { 'desc' : 'Auto dealers-Sales and service'},
            '432': { 'desc' : 'Service and Gas stations'},
            '433': { 'desc' : 'Auto body Tire shops Other related auto sales'},
            '434': { 'desc' : 'Automatic car wash'},
            '435': { 'desc' : 'Manual Car wash'},
            '436': { 'desc' : 'Self-service car wash'},
            '437': { 'desc' : 'Parking garage'},
            '438': { 'desc' : 'Parking lot'},
            '439': { 'desc' : 'Small parking garage'},
            '440': { 'desc' : 'Storage warehouse and Distribution facilities'},
            '441': { 'desc' : 'Fuel Storage and distribution facilities'},
            '442': { 'desc' : 'Mini warehouse(self storage'},
            '443': { 'desc' : 'Grain and feed elevators Mixers Sales outlets'},
            '444': { 'desc' : 'Lumber yards Sawmills'},
            '445': { 'desc' : 'Coal yards Bins'},
            '446': { 'desc' : 'Cold storage facilities'},
            '447': { 'desc' : 'Trucking terminals'},
            '448': { 'desc' : 'Piers Wharves Docks and Related facilities'},
            '449': { 'desc' : 'Other storage warehouse and distribution facilities'},
            '450': { 'desc' : 'Retail Services'},
            '451': { 'desc' : 'Regional Shopping centers'},
            '452': { 'desc' : 'Area or neighborhood shopping centres'},
            '453': { 'desc' : 'Large retail outlets'},
            '454': { 'desc' : 'Large retail food stores'},
            '455': { 'desc' : 'Dealerships-Sales and Service(other than auto with large sales operation'},
            '460': { 'desc' : 'Banks and Office buildings'},
            '461': { 'desc' : 'Standard Bank/Single occupant'},
            '462': { 'desc' : 'Drive-in branch bank'},
            '463': { 'desc' : 'Bank complex with office building'},
            '464': { 'desc' : 'office building'},
            '465': { 'desc' : 'Professional building'},
            '470': { 'desc' : 'Miscellaneous services'},
            '471': { 'desc' : 'Funeral homes'},
            '472': { 'desc' : 'Dog kennels Veterinary clinics'},
            '473': { 'desc' : 'Greenhouses'},
            '474': { 'desc' : 'Billboards'},
            '475': { 'desc' : 'Junkyards'},
            '480': { 'desc' : 'Multiple use or Multi-purpose'},
            '481': { 'desc' : 'Downtown row Type(with common wall)'},
            '482': { 'desc' : 'Downtown row type(detached)'},
            '483': { 'desc' : 'converted residence'},
            '484': { 'desc' : 'One story small structure'},
            '485': { 'desc' : 'One story small structure-Multi occupant'},
            '486': { 'desc' :'Minimart'},
            '500': { 'desc' : 'Recreation and Entertainment'},
            '510': { 'desc' : 'Entertainment Assembly'},
            '511': { 'desc' : 'Legitimate theaters'},
            '512': { 'desc' : 'Motion pictures theatres(excludes drive-in theatres'},
            '513': { 'desc' : 'Drive-in theatres'},
            '514': { 'desc' : 'Auditoriums exhibition and Exposition halls'},
            '515': { 'desc' : 'Radio T.V and Motion picture studios'},
            '520': { 'desc' : 'Sports assembly'},
            '521': { 'desc' :'Stadiums arenas armories Field houses'},
            '522': { 'desc' :'Racetracks'},
            '530': { 'desc' : 'Amusement Facilities'},
            '531': { 'desc' : "Fairgrounds"},
            '532': { 'desc' : 'Amusement parks'},
            '533': { 'desc' : 'Game farms'},
            '534': { 'desc' : 'Social organizations'},
            '540': { 'desc' : 'Indoor sports facilities'},
            '541': { 'desc' : 'Bowling centers'},
            '542': { 'desc' : 'Ice or roller skater rinks'},
            '543': { 'desc' : 'YMCAs YWCAs etc'},
            '544': { 'desc' : 'Health spas'},
            '545': { 'desc' : 'Indoor swimming pools'},
            '546': { 'desc' : 'other Indoor sports'},
            '550': { 'desc' : 'Outdoor Sports activities'},
            '551': { 'desc': 'Skiing centers'},
            '552': { 'desc' : 'Public golf courses'},
            '553': { 'desc' : 'Private Golf Country clubs'},
            '554': { 'desc' : 'Outdoor swimming pools'},
            '555': { 'desc' : 'residential stables'},
            '557': { 'desc' : 'Other outdoor sports'},
            '560': { 'desc' : 'Improved Beaches'},
            '570': { 'desc' : 'Marinas'},
            '580': { 'desc' : 'Camps Camping Facilities and resorts'},
            '581': { 'desc' : 'camps'},
            '582': { 'desc' : 'Camping Facilities'},
            '583': { 'desc' : 'Resort complexes'},
            '590': { 'desc' : 'Parks'},
            '591': { 'desc' : 'playgrounds'},
            '592': { 'desc' : 'Athletic fields'},
            '593': { 'desc' : 'Picnic grounds'},
            '600': { 'desc' : 'Community Services'},
            '610': { 'desc' : 'Education'},
            '611': { 'desc' : 'Libraries'},
            '612': { 'desc' : 'Schools'},
            '613': { 'desc' : 'Colleges and Universities'},
            '614': { 'desc' : 'Special schools and institutions'},
            '615': { 'desc' : 'Other Educational facilities'},
            '620': { 'desc' : 'Religious'},
            '630': { 'desc' : 'Welfare'},
            '631': { 'desc' : 'Orphanage'},
            '632': { 'desc' : 'Benevolent and moral associations'},
            '633': { 'desc' : 'Home for the aged'},
            '640': { 'desc' : 'Health'},
            '641': { 'desc' : 'Hospitals'},
            '642': { 'desc' : 'All other health facilities'},
            '650': { 'desc' : 'Government'},
            '651': {  'desc' : 'Highway garage'},
            '652': { 'desc' : 'Office building'},
            '653': { 'desc' : 'Parking lots'},
            '660': { 'desc' : 'Protection'},
            '661': { 'desc' : 'Army Navy Air force Marine and Coast Guard'},
            '662': { 'desc' : 'Police and fire protection Electrical Signal'},
            '670': { 'desc' : 'Correctional'},
            '680': { 'desc' : 'Cultural and Recreational'},
            '681': { 'desc' : 'Cultural facilities'},
            '682': { 'desc' : 'Recreational facilities'},
            '690': { 'desc' : 'Miscellaneous'},
            '691': { 'desc' : 'Professional Associations'},
            '692': { 'desc' : 'Roads Streets Highways and parkways Express or otherwise(if included) including adjoining land'},
            '693': { 'desc' : 'Indian Reservations'},
            '694': { 'desc' : 'Animal Welfare Shelters'},
            '695': { 'desc' : 'Cemeteries'},
            '700': { 'desc' : 'Industrial'},
            '710': { 'desc' : 'Manufacturing and Processing'},
            '712': { 'desc' : 'High tech manufacturing and processing'},
            '714': { 'desc' : 'Light industrial manufacturing and processing'},
            '715': { 'desc' : 'Heavy Manufacturing and Processing'},
            '720': { 'desc' : 'Mining and Quarrying'},
            '730': { 'desc' : 'Wells'},
            '731': { 'desc' : 'Oil-Natural Flow(for production)'},
            '732': { 'desc' : 'Oil- Forced Flow(for production)'},
            '733': { 'desc' : 'Gas(for production)'},
            '734': { 'desc' : 'Junk'},
            '735': { 'desc' : 'Water used for oil production'},
            '736': { 'desc' : 'Gas or oil storage wells'},
            '740': { 'desc' : 'Industrial Product pipelines'},
            '741': { 'desc' : 'Gas'},
            '742': { 'desc' : 'Water'},
            '743': { 'desc' : 'Brine'},
            '744': { 'desc' : 'Petroleum products'},
            '749': { 'desc' : 'other'},
            '800': { 'desc' : 'Public services'},
            '820': { 'desc' : 'Water'},
            '821': { 'desc' : 'Flood control'},
            '822': { 'desc' : 'Water Supply'},
            '823': { 'desc' : 'Water treatment facilities'},
            '826': { 'desc' : 'Water transmission improvements'},
            '827': { 'desc' : 'Water transmission outstanding plant'},
            '830': { 'desc' : 'Communication'},
            '831': { 'desc' : 'Telephone'},
            '832': { 'desc' : 'Telegraph'},
            '833': { 'desc' : 'Radio'},
            '834': { 'desc' : 'Television other than Community Antenna television'},
            '835': { 'desc' : 'Community Antenna Television'},
            '836': { 'desc' : 'Telephone outstanding plant'},
            '837': { 'desc' : 'Cellular telephone towers'},
            '840': { 'desc' : 'Transportation'},
            '841': { 'desc' : 'Motor Vehicle'},
            '842': { 'desc' : 'Ceiling railroad'},
            '843': { 'desc' : 'Non ceiling railroad'},
            '844': { 'desc' : 'Air'},
            '845': { 'desc' : 'Water'},
            '846': { 'desc' : 'Bridge tunnels and subways'},
            '847': { 'desc' : 'Pipelines'},
            '850': { 'desc' : 'Waste Disposal'},
            '851': { 'desc' : 'Soluble waste'},
            '852': { 'desc' : 'Landfill and dumps'},
            '853': { 'desc' : 'Sewage treatment and water pollution control'},
            '854': { 'desc' : 'Air pollution control'},
            '860': { 'desc' : 'Special Franchise property'},
            '861': { 'desc' : 'Electric and gas'},
            '862': { 'desc' : 'Water'},
            '866': { 'desc' : 'Telephone'},
            '867': { 'desc' : 'Miscellaneous'},
            '868': { 'desc' : 'Pipelines'},
            '869': { 'desc' : 'Television'},
            '870': { 'desc' : 'Electric and Gas'},
            '871': { 'desc' : 'Electric and Gas facilities'},
            '872': { 'desc' : 'Electric sub station Electric power generation facilities'},
            '873': { 'desc' : 'Gas measuring and regulation station'},
            '874': { 'desc' : 'Electric Power generation Facility - Hydro'},
            '875': { 'desc' : 'Electric Power generation Facility - Fossil Fuel'},
            '876': { 'desc' : 'Electric Power generation Facility - Nuclear'},
            '877': { 'desc' : 'Electric Power generation Facility - Other fuel'},
            '880': { 'desc' : 'Electric and Gas Transmission and distribution'},
            '882': { 'desc' : 'Electric transmission improvement'},
            '883': { 'desc' : 'Gas transmission improvement'},
            '884': { 'desc' : 'Electric distribution-Outstanding plant property'},
            '885': { 'desc' : 'Gas distribution - Outstanding plant property'},
            '900': { 'desc' : 'Wild Forested Conservation lands and public parks'},
            '910': { 'desc' : 'Private Wild and Forest Lands except for Private Hunting and Fishing Clubs'},
            '911': { 'desc' : 'Forest Land Under Section 480 of the Real Property Tax Law'},
            '912': { 'desc' : 'Forest Land Under Section 480-a of the Real Property Tax Law'},
            '920': { 'desc' : 'Private Hunting and Fishing Clubs'},
            '930': { 'desc' : 'State Owned Forest Lands'},
            '931': { 'desc' : 'State Owned Land (Forest Preserve) in the Adirondack or Catskill Parks Taxable Under Section 532-a of the Real Property Tax Law'},
            '932': { 'desc' : 'State Owned Land Other Than Forest Preserve Covered Under Section 532-b c d e f or g of the Real Property Tax Law'},
            '940': { 'desc' : 'Reforested Land and Other Related Conservation Purposes'},
            '941': { 'desc' : 'State Owned Reforested Land Taxable Under Sections 534 and 536 of the Real Property Tax Law'},
            '942': { 'desc' : 'County Owned Reforested Land'},
            '950': { 'desc' : 'Hudson River and Black River Regulating District Land'},
            '960': { 'desc' : 'Public Parks'},
            '961': { 'desc' : 'State Owned Public Parks Recreation Areas and Other Multiple Uses'},
            '962': { 'desc' : 'County Owned Public Parks and Recreation Areas'},
            '963': { 'desc' : 'City/Town/Village Public Parks and Recreation Areas'},
            '970': { 'desc' : 'Other Wild or Conservation Lands'},
            '971': { 'desc' : 'Wetlands Either Privately or Government Owned Subject to Specific Restrictions as to Use'},
            '972': { 'desc' : 'Land Under Water Either Privately or Government Owned (other than residential - more properly classified as value 315)'},
            '980': { 'desc' : 'Taxable State Owned Conservation Easements'},
            '990': { 'desc' : 'Other Taxable State Land Assessments'},
            '991': { 'desc' : 'Adirondack Park Aggregate Additional Assessments (Real Property Tax Law Section 542(3))'},
            '992': { 'desc' : 'Hudson River-Black River Regulating District Aggregate Additional Assessments (Environmental Conservation Law Section 15-2115)'},
            '993': { 'desc' : 'Transition Assessments for Taxable State Owned Land (Real Property Tax Law Section 545)'},
            '994': { 'desc' : 'Transition Assessments for Exempt State Owned Land (Real Property Tax Law Section 545)'}

        },
        'owner_type': {
            '1': {'desc':'Federal'},
            '2': {'desc':'State'},
            '3': {'desc':'County'},
            '4': {'desc':'City'},
            '5': {'desc':'Town'},
            '6': {'desc':'Village'},
            '7': {'desc':'Mixed Government'},
            '8': {'desc':'Private'},
            '9': {'desc':'Public School District or BOCES'},
            '10': {'desc': 'Road Right of Way'},
            '-999': {'desc':'Unknown'}
        },
        'bldg_style':{
            'A0': {'desc':'Cape Cod'},
            'A1': {'desc':'Two stories - Detached SM or MD'},
            'A2': {'desc':'One Story-permanent living quarter'},
            'A3': {'desc':'Large Suburban residence'},
            'A4': {'desc':'City residence one family'},
            'A5': {'desc':'One family attached or Semi detached'},
            'A6': {'desc':'Summer cottage'},
            'A7': {'desc':'Mansion type or town house'},
            'A8': {'desc':'Bungalow Colony-Cooperatively owned land'},
            'A9': {'desc':'Miscellaneous one family'},
            'B1': {'desc':'Two family brick'},
            'B2': {'desc':'Two family frame'},
            'B3': {'desc':'Two family converted from one family'},
            'B9': {'desc':'Miscellaneous Two family'},
            'C0': {'desc':'Three families'},
            'C1': {'desc':'Over six families without stories'},
            'C2': {'desc':'Five to six families'},
            'C3': {'desc':'Four families'},
            'C4': {'desc':'Old law tenement'},
            'C5': {'desc':'Converted dwelling or rooming house'},
            'C6': {'desc':'Walk-up cooperative'},
            'C7': {'desc':'Walk-up APT over six families with stores'},
            'C8': {'desc':'Walk up co-op conversion from loft/warehouse'},
            'C9': {'desc':'Garden Apartments'},
            'CM': {'desc':'Mobile homes/trailer parks'},
            'D0': {'desc':'Elevator Co-op conversion from loft/warehouse'},
            'D1': {'desc':'Elevator apt semi-fireproof without stores'},
            'D2': {'desc':'Elevator apt artists in residence'},
            'D3': {'desc':'Elevator apt fireproof without stores'},
            'D4': {'desc':'Elevator cooperative'},
            'D5': {'desc':'Elevator apt converted'},
            'D6': {'desc':'Elevator apt fireproof with stores'},
            'D7': {'desc':'Elevator apt semi-fireproof with stores'},
            'D8': {'desc':'Elevator apt luxury type'},
            'D9': {'desc':'Elevator apt miscellaneous'},
            'E1': {'desc':'Fireproof warehouse'},
            'E2': {'desc':'Contractors warehouse'},
            'E3': {'desc':'Semi-fireproof warehouse'},
            'E4': {'desc':'Metal frame warehouse'},
            'E7': {'desc':'Self-storage warehouse'},
            'E9': {'desc':'Miscellaneous warehouse'},
            'F1': {'desc':'Factory Heavy manufacturing-fireproof'},
            'F2': {'desc':'Factory Special Construction-fireproof'},
            'F4': {'desc':'Factory industrial semi-fireproof'},
            'F5': {'desc':'Factory light manufacturing'},
            'F8': {'desc':'Factory Tank farm'},
            'F9': {'desc':'Factory industrial miscellaneous'},
            'G0': {'desc':'Garage residential tax class 1 '},
            'G1': {'desc':'All parking garages'},
            'G2': {'desc':'Auto body/collision or Auto repair'},
            'G3': {'desc':'Gas station with retail store'},
            'G4': {'desc':'Gas station with service/auto repair'},
            'G5': {'desc':'Gas station only with/without small kiosk'},
            'G6': {'desc':'Licensed parking lot'},
            'G7': {'desc':'Unlicensed Parking lot'},
            'G8': {'desc':'Car sales/rental with showroom'},
            'G9': {'desc':'Miscellaneous garage or gas station'},
            'GU': {'desc':'Car sales or rental lots without showroom'},
            'GW': {'desc':'Car wash or lubritorium facility'},
            'HB': {'desc':'Boutique 10-100 rooms w/luxury facilities themed stylish w/full SVC accommodations'},
            'HH': {'desc':'Hostels-Bed rentals in dormitory-like settings w/shared rooms and bathrooms'},
            'HR': {'desc':'SRO- 1 OR 2 people housed in individual rooms in multiple dwelling affordable housing'},
            'HS': {'desc':'Extended Stay/Suite: Amenities similar to apt typically charge weekly rates and less expensive than full-service hotel'},
            'H1': {'desc':'Luxury Hotel'},
            'H2': {'desc':'Full-service hotel'},
            'H3': {'desc':'Limited service many affiliated with national chain'},
            'H4': {'desc':'Motel'},
            'H5': {'desc':'Hotel private club luxury type'},
            'H6': {'desc':'Apartment hotel'},
            'H7': {'desc':'Apartment hotel-cooperatively owned'},
            'H8': {'desc':'Dormitory'},
            'H9': {'desc':'Miscellaneous hotel'},
            'I1': {'desc':'Hospital Sanitorium and mental Institution'},
            'I2': {'desc':'Infirmary'},
            'I3': {'desc':'Dispensary'},
            'I4': {'desc':'Hospital and Staff facility'},
            'I5': {'desc':'Health Center child center and clinic'},
            'I6': {'desc':'Nursing Home'},
            'I7': {'desc':'Adult Care facility'},
            'I9': {'desc':'Miscellaneous hospital health care facility'},
            'J1': {'desc':'Theatre Art type less than 400 seats'},
            'J2': {'desc':'Theatre art type more than 400 seats'},
            'J3': {'desc':'Motion picture theatre with balcony'},
            'J4': {'desc':'Legitimate theatre sole use'},
            'J5': {'desc':'Theatre in mixed use building'},
            'J6': {'desc':'Television studio'},
            'J7': {'desc':'Off broadway type theatre'},
            'J8': {'desc':'Multiplex picture theatre'},
            'J9': {'desc':'Miscellaneous theatre'},
            'K1': {'desc':'One story retail building'},
            'K2': {'desc':'Multi-story retail building(2 or more)'},
            'K3': {'desc':'Multi-story department store'},
            'K4': {'desc':'Predominant retail with other uses'},
            'K5': {'desc':'Stand alone food establishments'},
            'K6': {'desc':'Shopping center with or without parking'},
            'K7': {'desc':'Banking facilities with or without parking'},
            'K8': {'desc':'Big box retail: not affixed and standing on own lot w/parking e.g Costco and BJ'},
            'K9': {'desc':'Miscellaneous store building'},
            'L1': {'desc':'Loft over 8 stories(mid Manh. type)'},
            'L2': {'desc':'Loft fireproof and storage type without stores'},
            'L3': {'desc':'Loft semi-fireproof'},
            'L8': {'desc':'Loft with retail stores other than type one'},
            'L9': {'desc':'Miscellaneous loft'},
            'M1': {'desc':'Church Synagogue and chapel'},
            'M2': {'desc':'Mission house(non-residential)'},
            'M3': {'desc':'Parsonage rectory'},
            'M4': {'desc':'Convent'},
            'M9': {'desc':'Miscellaneous religious facility'},
            'N1': {'desc':'Asylum'},
            'N2': {'desc':'Home for indigent children aged and homeless'},
            'N3': {'desc':'Orphanage'},
            'N4': {'desc':'detention house for wayward girls'},
            'N9': {'desc':'Miscellaneous asylum home'},
            'O1': {'desc':'Office only -1 story'},
            'O2': {'desc':'Office only 2 -6 stories'},
            'O3': {'desc':'Office only 7 -19 stories'},
            'O4': {'desc':'Office only with or without comm - 20 stories or more'},
            'O5': {'desc':'Office with comm- 1 to 6 stories'},
            'O6': {'desc':'Office with comm 7-19 stories'},
            'O7': {'desc':'Professional buildings/Stand alone Funeral homes'},
            'O8': {'desc':'Office with Apartments only'},
            'O9': {'desc':'Miscellaneous and old style bank buildings'},
            'P1': {'desc':'Concert halls'},
            'P2': {'desc':'Lodge room'},
            'P3': {'desc':'YWCA YMCA YWHA YMHA PAL'},
            'P4': {'desc':'Beach club'},
            'P5': {'desc':'Community center'},
            'P6': {'desc':'Amusement place bath house boat house'},
            'P7': {'desc':'Museum'},
            'P8': {'desc':'Library'},
            'P9': {'desc':'Miscellaneous indoor public assembly'},
            'Q1': {'desc':'Parks/Recreation facility'},
            'Q2': {'desc':'Playground'},
            'Q3': {'desc':'Outdoor pool'},
            'Q4': {'desc':'beach'},
            'Q5': {'desc':'Golf course'},
            'Q6': {'desc':'Stadium race track baseball field'},
            'Q7': {'desc':'Tennis court'},
            'Q8': {'desc':'Marina yacht club'},
            'Q9': {'desc':'Miscellaneous outdoor recreational facility'},
            'RA': {'desc':'Cultural medical educational etc'},
            'RB': {'desc':'Office space'},
            'RG': {'desc':'Indoor parking'},
            'RH': {'desc':'Hotel/Boatel'},
            'RK': {'desc':'Retail space'},
            'RP': {'desc':'Outdoor parking'},
            'RR': {'desc':'Condominium rentals'},
            'RS': {'desc':'Non-business storage space'},
            'RT': {'desc':'Terraces/Gardens/Cabanas'},
            'RW': {'desc':'Warehouse/Factory/Industrial'},
            'R0': {'desc':'Special Condominium billing lot'},
            'R1': {'desc':'Condo residential unit in 2-10 unit bldg'},
            'R2': {'desc':'Condo residential unit in walk-up bldg'},
            'R3': {'desc':'Condo residential unit in 1-3 story bldg'},
            'R4': {'desc':'Condo residential unit in elevator bldg'},
            'R5': {'desc':'Miscellaneous commercial'},
            'R6': {'desc':'Condo residential unit of 1-3 unit bldg-orig class 1'},
            'R7': {'desc':'Condo comml unit of 1-3 unit bldg-orig class 1'},
            'R8': {'desc':'condo comml unit of 2-10 unit bldg'},
            'R9': {'desc':'Co-op within a condominium'},
            'RR': {'desc':'Condo rentals'},
            'S0': {'desc':'Primarily 1 Family with 2 stores or offices'},
            'S1': {'desc':'Primarily 1 family with 1 store or office'},
            'S2': {'desc':'Primarily 2 family with 1 store or office '},
            'S3': {'desc':'Primarily 3 family with 1 store or office'},
            'S4': {'desc':'Primarily 4 family with 1 store or office'},
            'S5': {'desc':'Primarily 5-6 family with 1 store or office'},
            'S9': {'desc':'Single or multiple dwelling with stores or offices'},
            'T1': {'desc':'Airport airfield terminal'},
            'T2': {'desc':'pier dock bulkhead'},
            'T9': {'desc':'Miscellaneous transportation facility'},
            'U0': {'desc':'Utility company land and building'},
            'U1': {'desc':'Bridge  tunnel and highway'},
            'U2': {'desc':'Gas or electricity utility'},
            'U3': {'desc':'Ceiling railroad'},
            'U4': {'desc':'Telephone utility'},
            'U5': {'desc':'Communication facility other than telephone'},
            'U6': {'desc':'Railroad- private ownership'},
            'U7': {'desc':'Transportation- public ownership'},
            'U8': {'desc':'Revocable consent'},
            'U9': {'desc':'Miscellaneous utility property'},
            'V0': {'desc':'Zone residential not Manhattan'},
            'V1': {'desc':'Zoned commercial or Manhattan residential'},
            'V2': {'desc':'Zoned commercial adjacent to class 1 dwelling : not Manhattan'},
            'V3': {'desc':'Zoned primary residential : not Manhattan'},
            'V4': {'desc':'Police or Fire department'},
            'V5': {'desc':'School site or yard '},
            'V6': {'desc':'Library hospital or museum'},
            'V7': {'desc':'Port authority of New York and New Jersey'},
            'V8': {'desc':'New york state or US government'},
            'V9': {'desc':'Miscellaneous vacant land'},
            'W1': {'desc':'Public elementary Junior or Senior high'},
            'W2': {'desc':'Parochial school Yeshiva'},
            'W3': {'desc':'School or academy '},
            'W4': {'desc':'Training school'},
            'W5': {'desc':'City university'},
            'W6': {'desc':'Other college and university',
            'W7': {'desc':'Theological seminary'},
            'W8': {'desc':'Other private school'},
            'W9': {'desc':'Miscellaneous educational facility'},
            'Y1': {'desc':'Fire department'},
            'Y2': {'desc':'Police department'},
            'Y3': {'desc':'Prison jail house of detention'},
            'Y4': {'desc':'Military and Naval installation'},
            'Y5': {'desc':'Department of real estate'},
            'Y6': {'desc':'Department of sanitation'},
            'Y7': {'desc':'Department of ports and terminals'},
            'Y8': {'desc':'Department of public works'},
            'Y9': {'desc':'Department of environmental protection'},
            'Z0': {'desc':'Tennis cour pool shed etc'},
            'Z1': {'desc':'Court house'},
            'Z2': {'desc':'Public parking area'},
            'Z3': {'desc':'Post office'},
            'Z4': {'desc':'Foreign government'},
            'Z5': {'desc':'United nations'},
            'Z7': {'desc':'Easement'},
            'Z8': {'desc':'Cemetery'},
            'Z9': {'desc':'Other miscellaneous'}
        }

        }
}
